SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

CREATE DATABASE IF NOT EXISTS `DATA` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
USE `DATA`;

CREATE TABLE IF NOT EXISTS `telegram` (
`id` int(255) NOT NULL,
  `Channel` varchar(255) COLLATE utf8mb4_unicode_520_ci NOT NULL,
  `text` varchar(255) COLLATE utf8mb4_unicode_520_ci NOT NULL,
  `file` varchar(255) COLLATE utf8mb4_unicode_520_ci NOT NULL,
  `pubdate` timestamp NULL DEFAULT NULL,
  `unread` int(11) NOT NULL DEFAULT '1',
  `msgid` int(255) DEFAULT NULL,
  `obtained` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=MyISAM AUTO_INCREMENT=53 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci ROW_FORMAT=FIXED;

CREATE TABLE IF NOT EXISTS `twitterlinks` (
`id` int(11) NOT NULL,
  `link` varchar(255) DEFAULT NULL,
  `title` varchar(255) NOT NULL,
  `country` varchar(255) DEFAULT NULL,
  `feedid` int(11) DEFAULT NULL,
  `pubdate` datetime DEFAULT NULL,
  `read` int(11) DEFAULT '1',
  `obtained` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=MyISAM AUTO_INCREMENT=3173 DEFAULT CHARSET=utf8 ROW_FORMAT=FIXED;


ALTER TABLE `telegram`
 ADD PRIMARY KEY (`id`), ADD UNIQUE KEY `msgid` (`msgid`);

ALTER TABLE `twitterlinks`
 ADD PRIMARY KEY (`id`), ADD UNIQUE KEY `link` (`link`);


ALTER TABLE `telegram`
MODIFY `id` int(255) NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=53;
ALTER TABLE `twitterlinks`
MODIFY `id` int(11) NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=3173;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
